apiVersion: batch/v1
kind: Job
metadata:
  name: ml-job
  namespace: job-demo
spec:
  template:
    spec:
      containers:
      - name: pi
        image: heemok348/ml-job
        volumeMounts:
          - name: docker
            mountPath: /var/run/docker.sock
      restartPolicy: Never
      volumes:
        - name: docker
          hostPath:
            path: /var/run/docker.sock
            type: Socket
